spring:
  datasource:
    url: jdbc:mysql://192.168.56.102/springboot_sell?useUnicode=true&characterEncoding=utf8
    #url: jdbc:mysql://127.0.0.1/springboot_sell
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix:
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /sell



